nodes:
  Log4j-IP-Miner:
    inputs: []
    output: true
    prototype: log4j.IP
  Log4j-IP-Aggregator:
    inputs:
      - Log4j-IP-Miner
    output: true
    prototype: stdlib.aggregatorIPv4Generic
  Log4j-IP-Feed:
    inputs:
      - Log4j-IP-Aggregator
    output: false
    prototype: stdlib.feedGreenWithValue
